INSERT INTO users (id, full_name, email, email_verified_at, is_admin, password, address_id, cart_id, created_at,
                   updated_at)
VALUES ('d4b05a04-eac5-450e-8090-11ead22fa589',
        'Store Administrator',
        'admin@zamazor.com',
        CURRENT_TIMESTAMP,
        TRUE,
        '$2a$10$Jv.TgJLyd.VMRZrpjxBN9.Ut7W0kxH63/RwHeIvnmqoSpM3jTzg62', -- secret1234@
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('8bf4b301-0f1e-472b-ab13-c297680cc846',
        'Ayoub El Ouadifi',
        'ayoubelouadifi2005@gmail.com',
        CURRENT_TIMESTAMP,
        FALSE,
        '$2a$10$Jv.TgJLyd.VMRZrpjxBN9.Ut7W0kxH63/RwHeIvnmqoSpM3jTzg62',
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('3fa85f64-5717-4562-b3fc-2c963f66afa6',
        'Test User Unverified',
        'unverified.user@zamazor.com',
        NULL,
        FALSE,
        '$2a$10$Jv.TgJLyd.VMRZrpjxBN9.Ut7W0kxH63/RwHeIvnmqoSpM3jTzg62',
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);